### ISSUE TITLE
Use gh-pages for `demos` for metal-* components

### ISSUE THREAD

**Issue by cirocosta** [mairatma/metal-lerna#15]
Hey!

I've noticed that most of the `metal-*` repositories have a `demo(s)` directory, but they are just "runnable" if `git cloning` and then running the build steps. It'd be pretty cool to have them just one click away by using `gh-pages` to provide that. What do you think about setting a script for publishing them? There are various examples about travis integration that pushes to `gh-pages` when a push to master is done. 

Thx! 👯

**Comment by mairatma** [comment]
The plan so far was to have Metal.js's site include the demos, but we haven't managed to start working on that yet.

Your idea is very good though, and could be done even before the website is ready to include demos. We don't have travis set up for each repo yet either, but we could have a gulp task until that's ready, like we do for metaljs.com. What do you think @eduardolundgren and @zenorocha?

**Comment by cirocosta** [comment]
Cool! just as a reference, we have that in `wedeploy/io` for publishing the javadoc documentation: see https://github.com/wedeploy/io/blob/a787d2ad0c15ebb3727268cae2e96c90b72ef583/.publish-docs.sh and https://github.com/wedeploy/io/blob/a787d2ad0c15ebb3727268cae2e96c90b72ef583/.travis.yml#L20-L21

**Comment by zenorocha** [comment]
Yeah, we just need to make sure that these demos are going to be up to date.

**Comment by mairatma** [comment]
This issue was moved to metal/metal#133
